environment:
    matrix:
        - PYTHON: "C:\\Python35"
        - PYTHON: "C:\\Python36"
        - PYTHON: "C:\\Python37"

build: off

install:
    - set PATH=%PYTHON%;%PATH

before_test:
    - python -v

test_script:
    - python -m unittest discover -v
